import { ApiProperty } from '@nestjs/swagger';
import { RawDataDTO } from './rawdata.dto';
import { StructuredSummaryDTO } from './structured-summary.dto';

export class StructuredResponseDTO {
  @ApiProperty({
    type: StructuredSummaryDTO,
    description:
      'Structured summary with clean answers for key business questions.',
  })
  summary: StructuredSummaryDTO;

  @ApiProperty({
    type: RawDataDTO,
    description: 'Raw scraped website data, cleaned and trimmed.',
  })
  rawData: RawDataDTO;

  @ApiProperty({
    example: `1. **What product or service does this website offer?**\n   - ...\n2. **What category of business is it in?**\n   - ...`,
    description: 'Original raw text generated by the LLM before parsing.',
  })
  rawText: string;
}
